name: Update dependencies
on:
  schedule:
    - cron: "6 8 26 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - uses: actions/setup-python@v5

      - uses: abatilo/actions-poetry@v3.0.0
      - run: poetry update --lock

      - id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updates dependencies

      - if: ${{ steps.commit-and-push.outputs.changes_detected == false }}
        run: gh run cancel ${{ github.run_id }} && tail -f /dev/null
        env:
          GITHUB_TOKEN: ${{ github.token }}

  run-tests:
    needs: [update]
    uses: delb-xml/snakesist/.github/workflows/tests.yml@main
    with:
      ref: main
